# Generated by Django 4.2.3 on 2023-07-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='usersobrenome',
        ),
    ]
