# Generated by Django 4.2.3 on 2023-07-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_usertest_usersobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='useronlytest',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
            ],
        ),
    ]
