# Generated by Django 4.2.3 on 2023-07-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_useronlytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useronlytest',
        ),
    ]
