# Generated by Django 4.2.3 on 2023-07-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_delete_useronlytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='usersobrenome',
            field=models.CharField(default='Sobrenome', max_length=25),
        ),
    ]
