# Generated by Django 4.2.3 on 2023-07-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_usertest_usersobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='cpf',
            field=models.CharField(default=None, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertest',
            name='telefone',
            field=models.CharField(default=None, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertest',
            name='useremail',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertest',
            name='userpassword',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertest',
            name='usersobrenome',
            field=models.CharField(max_length=25),
        ),
    ]
