# Generated by Django 4.2.3 on 2023-07-28 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_usertest_cpf_usertest_telefone_usertest_useremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='datacriacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
