# Generated by Django 4.2.3 on 2023-07-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=35)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
    ]
